<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class HotelRoomSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();

        $rooms = [
            // InterContinental Đà Nẵng (hotel_id = 1)
            [
                'hotel_id' => 1,
                'name' => 'Classic Room',
                'price_per_night' => 8000000,
                'discount_percent' => 10,
                'capacity' => 2,
                'quantity' => 10,
                'bed_type' => 'King Bed',
                'area' => 45,
                'dynamic_price' => json_encode(['weekend' => 9000000]),
                'description' => 'Phòng tiêu chuẩn view biển',
            ],
            [
                'hotel_id' => 1,
                'name' => 'Villa Ocean View',
                'price_per_night' => 15000000,
                'discount_percent' => 15,
                'capacity' => 4,
                'quantity' => 5,
                'bed_type' => 'King + Twin',
                'area' => 120,
                'dynamic_price' => json_encode(['holiday' => 18000000]),
                'description' => 'Biệt thự riêng view biển',
            ],

            // Lotte Hà Nội (hotel_id = 2)
            [
                'hotel_id' => 2,
                'name' => 'Deluxe Room',
                'price_per_night' => 2500000,
                'discount_percent' => 5,
                'capacity' => 2,
                'quantity' => 20,
                'bed_type' => 'King Bed',
                'area' => 40,
                'dynamic_price' => json_encode(['weekend' => 2800000]),
                'description' => 'Phòng cao cấp view thành phố',
            ],
            [
                'hotel_id' => 2,
                'name' => 'Suite Room',
                'price_per_night' => 5000000,
                'discount_percent' => 10,
                'capacity' => 3,
                'quantity' => 8,
                'bed_type' => 'King Bed',
                'area' => 80,
                'dynamic_price' => json_encode(['holiday' => 5500000]),
                'description' => 'Phòng suite sang trọng',
            ],

            // Vinpearl Hạ Long (hotel_id = 3)
            [
                'hotel_id' => 3,
                'name' => 'Deluxe Sea View',
                'price_per_night' => 3000000,
                'discount_percent' => 10,
                'capacity' => 2,
                'quantity' => 15,
                'bed_type' => 'Double Bed',
                'area' => 42,
                'dynamic_price' => null,
                'description' => 'View vịnh Hạ Long',
            ],
            [
                'hotel_id' => 3,
                'name' => 'Executive Suite',
                'price_per_night' => 6000000,
                'discount_percent' => 15,
                'capacity' => 3,
                'quantity' => 6,
                'bed_type' => 'King Bed',
                'area' => 90,
                'dynamic_price' => json_encode(['holiday' => 6500000]),
                'description' => 'Phòng suite cao cấp',
            ],

            // Đà Lạt Palace (hotel_id = 4)
            [
                'hotel_id' => 4,
                'name' => 'Superior Room',
                'price_per_night' => 2000000,
                'discount_percent' => 5,
                'capacity' => 2,
                'quantity' => 12,
                'bed_type' => 'Queen Bed',
                'area' => 35,
                'dynamic_price' => null,
                'description' => 'Phong cách cổ điển Pháp',
            ],
            [
                'hotel_id' => 4,
                'name' => 'Luxury Suite',
                'price_per_night' => 4000000,
                'discount_percent' => 10,
                'capacity' => 3,
                'quantity' => 5,
                'bed_type' => 'King Bed',
                'area' => 70,
                'dynamic_price' => json_encode(['weekend' => 4500000]),
                'description' => 'Phòng rộng sang trọng',
            ],

            // JW Marriott Phú Quốc (hotel_id = 5)
            [
                'hotel_id' => 5,
                'name' => 'Emerald Bay Room',
                'price_per_night' => 7000000,
                'discount_percent' => 15,
                'capacity' => 2,
                'quantity' => 10,
                'bed_type' => 'King Bed',
                'area' => 50,
                'dynamic_price' => json_encode(['weekend' => 7500000]),
                'description' => 'View biển tuyệt đẹp',
            ],
            [
                'hotel_id' => 5,
                'name' => 'Pool Villa',
                'price_per_night' => 14000000,
                'discount_percent' => 20,
                'capacity' => 4,
                'quantity' => 4,
                'bed_type' => 'King + Twin',
                'area' => 150,
                'dynamic_price' => json_encode(['holiday' => 16000000]),
                'description' => 'Villa hồ bơi riêng',
            ],
            [
                'hotel_id' => 6,
                'name' => 'River View Room',
                'price_per_night' => 3200000,
                'discount_percent' => 10,
                'capacity' => 2,
                'quantity' => 8,
                'bed_type' => 'King Bed',
                'area' => 32,
                'dynamic_price' => json_encode(['weekend' => 3600000]),
                'description' => 'Phòng nhìn ra sông Chao Phraya',
            ],
            [
                'hotel_id' => 7,
                'name' => 'Deluxe Mekong Room',
                'price_per_night' => 2800000,
                'discount_percent' => 10,
                'capacity' => 2,
                'quantity' => 10,
                'bed_type' => 'King Bed',
                'area' => 35,
                'dynamic_price' => json_encode(['weekend' => 3000000]),
                'description' => 'Phòng tiêu chuẩn trung tâm Viêng Chăn',
            ],
            [
                'hotel_id' => 8,
                'name' => 'Khmer Deluxe Room',
                'price_per_night' => 1900000,
                'discount_percent' => 15,
                'capacity' => 2,
                'quantity' => 12,
                'bed_type' => 'Double Bed',
                'area' => 38,
                'dynamic_price' => json_encode(['holiday' => 2200000]),
                'description' => 'Phòng tiện nghi gần khu Angkor',
            ],
            [
                'hotel_id' => 9,
                'name' => 'Ubud Garden Villa',
                'price_per_night' => 4200000,
                'discount_percent' => 15,
                'capacity' => 2,
                'quantity' => 7,
                'bed_type' => 'King Bed',
                'area' => 48,
                'dynamic_price' => json_encode(['weekend' => 4600000]),
                'description' => 'Villa yên tĩnh giữa thiên nhiên Bali',
            ],
            [
                'hotel_id' => 10,
                'name' => 'Tokyo Skytree View Room',
                'price_per_night' => 3900000,
                'discount_percent' => 10,
                'capacity' => 2,
                'quantity' => 9,
                'bed_type' => 'Twin Bed',
                'area' => 30,
                'dynamic_price' => json_encode(['holiday' => 4300000]),
                'description' => 'Phòng hiện đại nhìn ra Tokyo Skytree',
            ],
            [
                'hotel_id' => 11,
                'name' => 'Marina Bay Premier',
                'price_per_night' => 7800000,
                'discount_percent' => 12,
                'capacity' => 2,
                'quantity' => 10,
                'bed_type' => 'King Bed',
                'area' => 42,
                'dynamic_price' => json_encode(['weekend' => 8500000]),
                'description' => 'Phòng cao cấp ngay khu Merlion Park',
            ],
            [
                'hotel_id' => 12,
                'name' => 'Forbidden City Deluxe',
                'price_per_night' => 2600000,
                'discount_percent' => 10,
                'capacity' => 2,
                'quantity' => 12,
                'bed_type' => 'Queen Bed',
                'area' => 34,
                'dynamic_price' => json_encode(['holiday' => 2900000]),
                'description' => 'Phòng thuận tiện cho tour Bắc Kinh trung tâm',
            ],
            [
                'hotel_id' => 13,
                'name' => 'Myeongdong City View',
                'price_per_night' => 3500000,
                'discount_percent' => 10,
                'capacity' => 2,
                'quantity' => 11,
                'bed_type' => 'Double Bed',
                'area' => 31,
                'dynamic_price' => json_encode(['weekend' => 3900000]),
                'description' => 'Phòng trung tâm Seoul thuận tiện mua sắm',
            ],
            [
                'hotel_id' => 14,
                'name' => 'Patong Deluxe Room',
                'price_per_night' => 3400000,
                'discount_percent' => 12,
                'capacity' => 2,
                'quantity' => 12,
                'bed_type' => 'King Bed',
                'area' => 38,
                'dynamic_price' => json_encode(['weekend' => 3800000]),
                'description' => 'Phòng nghỉ thoải mái gần biển Patong, hợp tour nghỉ dưỡng ngắn ngày',
            ],
            [
                'hotel_id' => 14,
                'name' => 'Family Pool Access',
                'price_per_night' => 5200000,
                'discount_percent' => 10,
                'capacity' => 4,
                'quantity' => 5,
                'bed_type' => 'King + Twin',
                'area' => 52,
                'dynamic_price' => json_encode(['holiday' => 5900000]),
                'description' => 'Phòng gia đình có lối ra hồ bơi riêng tiện cho khách đi cùng trẻ nhỏ',
            ],
            [
                'hotel_id' => 15,
                'name' => 'Gion Superior Twin',
                'price_per_night' => 5200000,
                'discount_percent' => 10,
                'capacity' => 2,
                'quantity' => 8,
                'bed_type' => 'Twin Bed',
                'area' => 34,
                'dynamic_price' => json_encode(['weekend' => 5600000]),
                'description' => 'Phòng yên tĩnh phong cách Kyoto, thuận tiện đi bộ tham quan khu Gion',
            ],
            [
                'hotel_id' => 15,
                'name' => 'Kyoto Premier Double',
                'price_per_night' => 6800000,
                'discount_percent' => 12,
                'capacity' => 3,
                'quantity' => 4,
                'bed_type' => 'Queen Bed',
                'area' => 45,
                'dynamic_price' => json_encode(['holiday' => 7300000]),
                'description' => 'Phòng cao cấp rộng rãi phù hợp khách muốn trải nghiệm lưu trú tinh tế tại cố đô',
            ],
            [
                'hotel_id' => 16,
                'name' => 'Jeju Standard Ocean Breeze',
                'price_per_night' => 3100000,
                'discount_percent' => 10,
                'capacity' => 2,
                'quantity' => 10,
                'bed_type' => 'Double Bed',
                'area' => 33,
                'dynamic_price' => json_encode(['weekend' => 3500000]),
                'description' => 'Phòng tiêu chuẩn sáng sủa, thuận tiện nghỉ ngơi sau ngày tham quan đảo',
            ],
            [
                'hotel_id' => 16,
                'name' => 'Jeju Family Suite',
                'price_per_night' => 4700000,
                'discount_percent' => 10,
                'capacity' => 4,
                'quantity' => 5,
                'bed_type' => 'King + Twin',
                'area' => 48,
                'dynamic_price' => json_encode(['holiday' => 5300000]),
                'description' => 'Suite gia đình phù hợp nhóm khách nghỉ dưỡng kết hợp khám phá Jeju',
            ],
        ];

        foreach ($rooms as &$room) {
            $room['created_at'] = $now;
            $room['updated_at'] = $now;
        }

        DB::table('hotel_rooms')->insert($rooms);
    }
}