<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class HotelSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();

        $hotels = [
            [
                'location_id' => 1,
                'name' => 'InterContinental Danang Sun Peninsula Resort',
                'rating' => 4.9,
                'reviews_count' => 2500,
                'rating_text' => 'Xuất sắc',
                'price_per_night' => 8000000,
                'discount_percent' => 15,
                'is_promotion' => true,
                'promotion_end' => '2026-12-31 23:59:59',
                'combo_content' => 'Gói nghỉ dưỡng bao gồm buffet sáng thượng hạng tại nhà hàng Citron, xe đưa đón sân bay riêng biệt, trà chiều miễn phí, ưu đãi 20% các dịch vụ Spa tại HARNN Heritage, quyền sử dụng hồ bơi vô cực, bãi biển riêng và nhiều không gian nghỉ dưỡng cao cấp phù hợp cho kỳ nghỉ sang trọng tại bán đảo Sơn Trà.',
                'description' => 'Tọa lạc tại bán đảo Sơn Trà, đây là kiệt tác của kiến trúc sư Bill Bensley. Resort trải dài qua 4 tầng: Heaven, Sky, Earth và Sea, mang đến không gian nghỉ dưỡng biệt lập với view biển 180 độ, rất phù hợp cho khách cao cấp muốn kết hợp nghỉ dưỡng riêng tư và trải nghiệm dịch vụ sang trọng.',
                'amenities' => json_encode(['Hồ bơi vô cực', 'HARNN Heritage Spa', 'Phòng Gym hiện đại', 'Bãi biển riêng', 'Câu lạc bộ trẻ em', 'Rạp chiếu phim']),
                'image_url' => 'https://duan-sungroup.com/wp-content/uploads/2022/12/intercontinental-da-nang-sun-peninsula-resort-leading.png',
                'address' => 'Bãi Bắc, Sơn Trà, Đà Nẵng',
                'lat' => 16.117700,
                'lng' => 108.294300,
            ],
            [
                'location_id' => 3,
                'name' => 'Lotte Hotel Hanoi',
                'rating' => 4.8,
                'reviews_count' => 3200,
                'rating_text' => 'Xuất sắc',
                'price_per_night' => 2500000,
                'discount_percent' => 10,
                'is_promotion' => true,
                'promotion_end' => '2026-11-30 23:59:59',
                'combo_content' => 'Ưu đãi đặt phòng bao gồm vé tham quan đài quan sát Sky Walk, miễn phí sử dụng hồ bơi bốn mùa và sauna, giảm 10% tại các nhà hàng trong khách sạn, hỗ trợ check-in thuận tiện cho khách công tác hoặc khách du lịch và quyền sử dụng các tiện ích tiêu chuẩn cao ngay trung tâm Hà Nội.',
                'description' => 'Nằm từ tầng 33 đến tầng 65 của tòa nhà Lotte Center hiện đại, Lotte Hotel Hanoi là sự kết nối giữa khu phố cổ lâu đời và khu đô thị mới đang phát triển, rất phù hợp cho khách công tác lẫn khách du lịch muốn ở trung tâm với tiêu chuẩn dịch vụ cao.',
                'amenities' => json_encode(['Hồ bơi bốn mùa', 'Trung tâm thể hình', 'Nhà hàng Top of Hanoi', 'Bar tầng thượng', 'Dịch vụ Spa', 'Business Center']),
                'image_url' => 'https://i.ex-cdn.com/theinvestor.vn/files/content/2022/06/20/lottehotel-1200x809-1022.jpg',
                'address' => '54 Liễu Giai, Ba Đình, Hà Nội',
                'lat' => 21.033400,
                'lng' => 105.813200,
            ],
            [
                'location_id' => 6,
                'name' => 'Vinpearl Resort & Spa Hạ Long',
                'rating' => 4.7,
                'reviews_count' => 1800,
                'rating_text' => 'Rất tốt',
                'price_per_night' => 3000000,
                'discount_percent' => 20,
                'is_promotion' => true,
                'promotion_end' => '2026-10-30 23:59:59',
                'combo_content' => 'Combo kỳ nghỉ bao gồm vé tham quan vịnh Hạ Long, buffet sáng tiêu chuẩn 5 sao, miễn phí tàu cao tốc ra đảo Rều, voucher sử dụng dịch vụ Vincharm Spa, quyền dùng hồ bơi ngoài trời, bãi biển nhân tạo và không gian nghỉ dưỡng phù hợp cho gia đình hoặc cặp đôi muốn tận hưởng Hạ Long theo phong cách resort.',
                'description' => 'Được lấy cảm hứng từ nhà hát thành phố Rennes (Pháp), Vinpearl Hạ Long như một lâu đài tráng lệ nổi trên mặt biển với 4 mặt giáp vịnh, mang lại cảm giác nghỉ dưỡng sang trọng và rất hợp cho khách muốn trải nghiệm Hạ Long theo phong cách resort cao cấp.',
                'amenities' => json_encode(['Hồ bơi ngoài trời', 'Vincharm Spa', 'Bãi biển nhân tạo', 'Nhà hàng Akoya', 'Khu vui chơi trẻ em']),
                'image_url' => 'https://statics.vinpearl.com/HL_1730783888.jpg',
                'address' => 'Đảo Rều, Hạ Long',
                'lat' => 20.957700,
                'lng' => 107.044900,
            ],
            [
                'location_id' => 7,
                'name' => 'Dalat Palace Heritage Hotel',
                'rating' => 4.6,
                'reviews_count' => 1400,
                'rating_text' => 'Tuyệt vời',
                'price_per_night' => 2000000,
                'discount_percent' => 5,
                'is_promotion' => true,
                'promotion_end' => '2026-09-15 23:59:59',
                'combo_content' => 'Nghỉ dưỡng phong cách hoàng gia với bữa sáng kiểu Pháp tại nhà hàng Le Rabelais, trà chiều trong khuôn viên sân vườn cổ kính, quyền sử dụng các tiện ích nghỉ dưỡng truyền thống và không gian lưu trú mang dấu ấn lịch sử đặc biệt phù hợp cho kỳ nghỉ nhẹ nhàng tại trung tâm Đà Lạt.',
                'description' => 'Xây dựng từ năm 1922, Dalat Palace là biểu tượng cho sự sang trọng mang đậm dấu ấn kiến trúc Pháp cổ điển nhìn thẳng ra hồ Xuân Hương, đặc biệt phù hợp với du khách yêu phong cách lưu trú cổ điển, yên tĩnh và nhiều giá trị lịch sử.',
                'amenities' => json_encode(['Sân vườn rộng lớn', 'Nhà hàng Le Rabelais', 'Hầm rượu vang', 'Dịch vụ Massage', 'Sân Tennis']),
                'image_url' => 'https://cf.bstatic.com/xdata/images/hotel/max1024x768/680499762.jpg?k=3b9add0bca4625414ebec50dc7d564addcd9e1b387998191e49933ab081b15a0&o=',
                'address' => '02 Trần Phú, Đà Lạt',
                'lat' => 11.940500,
                'lng' => 108.441700,
            ],
            [
                'location_id' => 8,
                'name' => 'JW Marriott Phu Quoc Emerald Bay',
                'rating' => 4.9,
                'reviews_count' => 2100,
                'rating_text' => 'Xuất sắc',
                'price_per_night' => 7000000,
                'discount_percent' => 25,
                'is_promotion' => true,
                'promotion_end' => '2026-12-01 23:59:59',
                'combo_content' => 'Ưu đãi đặc biệt bao gồm tham gia lớp học làm đèn lồng và nấu ăn, giảm 25% giá phòng cho kỳ nghỉ trên 3 đêm, tặng 01 liệu trình massage, quyền sử dụng hồ bơi, bãi biển riêng, các hoạt động nghỉ dưỡng cao cấp và nhiều tiện ích đặc trưng làm nên trải nghiệm nổi bật tại Bãi Khem.',
                'description' => 'Với concept là một trường đại học cổ giả tưởng, resort mang đến trải nghiệm thị giác kinh ngạc tọa lạc tại Bãi Khem - bãi biển đẹp nhất Phú Quốc, rất phù hợp cho khách muốn vừa nghỉ dưỡng cao cấp vừa có nhiều góc chụp ảnh ấn tượng và trải nghiệm dịch vụ đẳng cấp.',
                'amenities' => json_encode(['Hồ bơi vỏ sò', 'Chanterelle Spa', 'Bãi biển riêng biệt', 'Nhà hàng Pink Pearl', 'Lớp học yoga', 'Trung tâm thể thao nước']),
                'image_url' => 'https://duan-sungroup.com/wp-content/uploads/2022/12/JW-Marriott-Phu-Quoc-Emerald-Bay-Resort-leading.png',
                'address' => 'Bãi Khem, Phú Quốc',
                'lat' => 10.029800,
                'lng' => 104.031800,
            ],
            [
                'location_id' => 9,
                'name' => 'Riva Arun Bangkok',
                'rating' => 4.7,
                'reviews_count' => 980,
                'rating_text' => 'Rất tốt',
                'price_per_night' => 3200000,
                'discount_percent' => 10,
                'is_promotion' => true,
                'promotion_end' => '2026-11-30 23:59:59',
                'combo_content' => 'Gói lưu trú bao gồm phòng view sông Chao Phraya, bữa sáng kiểu Thái, hỗ trợ đưa đón tuk tuk đến khu Grand Palace, quyền sử dụng rooftop bar và vị trí rất thuận lợi để kết nối các điểm tham quan ven sông nổi tiếng của Bangkok trong lịch trình ngắn ngày.',
                'description' => 'Khách sạn boutique ven sông với tầm nhìn Wat Arun cực đẹp, thuận tiện cho lịch trình khám phá Bangkok cổ kính và phù hợp với du khách thích không gian nhỏ gọn, tinh tế nhưng vẫn có vị trí rất đắt giá ngay khu trung tâm ven sông.',
                'amenities' => json_encode(['Rooftop bar', 'Bữa sáng', 'Xe đưa đón nội khu', 'Wifi miễn phí']),
                'image_url' => 'https://images.trvl-media.com/lodging/16000000/15460000/15452200/15452130/4c486ff6.jpg?impolicy=resizecrop&rw=575&rh=575&ra=fill',
                'address' => '392/25-26 Maharaj Road, Bangkok',
                'lat' => 13.744700,
                'lng' => 100.491200,
            ],
            [
                'location_id' => 15,
                'name' => 'Crowne Plaza Vientiane',
                'rating' => 4.6,
                'reviews_count' => 760,
                'rating_text' => 'Rất tốt',
                'price_per_night' => 2800000,
                'discount_percent' => 10,
                'is_promotion' => true,
                'promotion_end' => '2026-10-31 23:59:59',
                'combo_content' => 'Bao gồm buffet sáng, xe đưa đón sân bay, ưu đãi sử dụng hồ bơi ngoài trời, quyền tiếp cận khu gym và các dịch vụ cơ bản phù hợp cho đoàn khách đi tour Lào ngắn ngày cần nơi lưu trú gọn gàng, hiện đại và thuận tiện di chuyển.',
                'description' => 'Khách sạn hiện đại tại trung tâm Viêng Chăn, phù hợp cho đoàn khách đi tour Lào ngắn ngày nhờ vị trí thuận tiện, phòng ốc gọn gàng và dịch vụ ổn định, dễ đáp ứng nhu cầu của cả khách đoàn lẫn khách gia đình.',
                'amenities' => json_encode(['Hồ bơi', 'Phòng gym', 'Nhà hàng quốc tế', 'Xe sân bay']),
                'image_url' => 'https://res.klook.com/klook-hotel/image/upload/w_750,c_fill,q_85/travelapi/14000000/13070000/13065300/13065295/5ff92a73_z.jpg',
                'address' => 'Samsenthai Road, Chanthabouly, Vientiane',
                'lat' => 17.958100,
                'lng' => 102.592900,
            ],
            [
                'location_id' => 18,
                'name' => 'Somadevi Angkor Resort & Spa',
                'rating' => 4.5,
                'reviews_count' => 1240,
                'rating_text' => 'Rất tốt',
                'price_per_night' => 1900000,
                'discount_percent' => 15,
                'is_promotion' => true,
                'promotion_end' => '2026-09-20 23:59:59',
                'combo_content' => 'Gói lưu trú kèm buffet sáng, xe tuk tuk ra Pub Street, voucher massage chân 30 phút, quyền sử dụng hồ bơi và các tiện ích nghỉ dưỡng cơ bản rất phù hợp cho du khách cần thư giãn sau những buổi tham quan Angkor kéo dài.',
                'description' => 'Khu nghỉ dưỡng gần quần thể Angkor, cân bằng giữa tiện nghi hiện đại và phong cách Khmer truyền thống, rất phù hợp cho du khách muốn có nơi nghỉ thoải mái sau các ngày tham quan di tích kéo dài và di chuyển nhiều.',
                'amenities' => json_encode(['Hồ bơi', 'Spa', 'Nhà hàng Khmer', 'Xe tuk tuk đưa đón']),
                'image_url' => 'https://z.cdrst.com/foto/hotel-sf/12102e8f/granderesp/foto-hotel-121023e5.jpg',
                'address' => 'Sivatha Blvd, Siem Reap',
                'lat' => 13.361600,
                'lng' => 103.856600,
            ],
            [
                'location_id' => 21,
                'name' => 'Maya Ubud Resort & Spa',
                'rating' => 4.8,
                'reviews_count' => 1680,
                'rating_text' => 'Xuất sắc',
                'price_per_night' => 4200000,
                'discount_percent' => 15,
                'is_promotion' => true,
                'promotion_end' => '2026-12-15 23:59:59',
                'combo_content' => 'Gói nghỉ dưỡng gồm yoga sáng, trà chiều miễn phí, shuttle bus đến trung tâm Ubud, quyền sử dụng hồ bơi vô cực, không gian spa thư giãn và nhiều tiện ích phù hợp cho khách yêu thiên nhiên, thích nghỉ dưỡng chậm và trải nghiệm Bali theo hướng yên tĩnh hơn.',
                'description' => 'Resort nằm bên thung lũng xanh mướt, nổi bật với hồ bơi vô cực và không gian nghỉ dưỡng đặc trưng Bali, rất phù hợp cho khách yêu thiên nhiên, thích nghỉ chậm và muốn tận hưởng cảm giác thư giãn đúng chất Ubud.',
                'amenities' => json_encode(['Hồ bơi vô cực', 'Spa', 'Lớp yoga', 'Xe đưa đón trung tâm']),
                'image_url' => 'https://static51.com-hotel.com/uploads/hotel/59844/photo/maya-ubud-resort-spa_155685576017.jpg',
                'address' => 'Jl. Gunung Sari, Peliatan, Ubud, Bali',
                'lat' => -8.532100,
                'lng' => 115.274200,
            ],
            [
                'location_id' => 25,
                'name' => 'Asakusa View Hotel',
                'rating' => 4.7,
                'reviews_count' => 1540,
                'rating_text' => 'Xuất sắc',
                'price_per_night' => 3900000,
                'discount_percent' => 10,
                'is_promotion' => true,
                'promotion_end' => '2026-11-10 23:59:59',
                'combo_content' => 'Bao gồm buffet sáng kiểu Nhật, vé shuttle bus, hỗ trợ gửi hành lý miễn phí, vị trí thuận tiện để tham quan khu Asakusa và các tiện ích lưu trú phù hợp cho khách muốn khám phá Tokyo theo cách thoải mái nhưng vẫn tiết kiệm thời gian di chuyển.',
                'description' => 'Khách sạn cao tầng gần Asakusa với góc nhìn đẹp ra Tokyo Skytree, thuận tiện di chuyển đến Senso-ji và phù hợp cho khách du lịch muốn ở khu vực vừa dễ tham quan vừa có cảm giác rõ nét về nhịp sống Tokyo.',
                'amenities' => json_encode(['Buffet sáng', 'Sky lounge', 'Wifi tốc độ cao', 'Phòng gia đình']),
                'image_url' => 'https://cf.bstatic.com/xdata/images/hotel/max1024x768/420187017.jpg?k=a311b971578467b3cc73c7514252f102f682488d9ba20b77b57c76dfc13f996b&o=',
                'address' => '3-17-1 Nishiasakusa, Taito City, Tokyo',
                'lat' => 35.714600,
                'lng' => 139.790400,
            ],
            [
                'location_id' => 32,
                'name' => 'Fullerton Hotel Singapore',
                'rating' => 4.8,
                'reviews_count' => 2860,
                'rating_text' => 'Xuất sắc',
                'price_per_night' => 7800000,
                'discount_percent' => 12,
                'is_promotion' => true,
                'promotion_end' => '2026-09-25 23:59:59',
                'combo_content' => 'Gói lưu trú gồm buffet sáng, credit dùng tại rooftop bar, vị trí đi bộ vài phút tới Merlion Park, quyền sử dụng các tiện ích cao cấp trong khách sạn và lợi thế di chuyển rất nhanh đến các điểm nổi bật quanh khu Marina Bay của Singapore.',
                'description' => 'Khách sạn biểu tượng tại khu Marina, phù hợp cho hành trình Singapore ngắn ngày với vị trí rất trung tâm, dịch vụ cao cấp và lợi thế lớn trong việc kết nối các điểm tham quan nổi bật quanh vịnh Marina Bay.',
                'amenities' => json_encode(['Hồ bơi', 'Gym', 'Rooftop dining', 'Khu trung tâm']),
                'image_url' => 'https://images.getaroom-cdn.com/image/upload/s--ltU6_baC--/c_limit,e_improve,fl_lossy.immutable_cache,h_460,q_auto:good,w_460/v1709447826/8e8612515949aa10dcb1048d1d614edcfcf042ef?_a=BACAEuEv&atc=e7cd1cfa',
                'address' => '1 Fullerton Square, Singapore',
                'lat' => 1.286700,
                'lng' => 103.853800,
            ],
            [
                'location_id' => 35,
                'name' => 'Sunworld Hotel Beijing',
                'rating' => 4.5,
                'reviews_count' => 1100,
                'rating_text' => 'Rất tốt',
                'price_per_night' => 2600000,
                'discount_percent' => 10,
                'is_promotion' => true,
                'promotion_end' => '2026-10-20 23:59:59',
                'combo_content' => 'Có buffet sáng, xe đón điểm hẹn city tour, ưu đãi check-in sớm nếu còn phòng, hỗ trợ lưu trú thuận tiện cho khách tham quan Bắc Kinh và vị trí phù hợp để kết hợp các hoạt động tham quan, mua sắm và ăn uống trong khu trung tâm.',
                'description' => 'Khách sạn tại khu Wangfujing, tiện cho lịch trình tham quan Tử Cấm Thành và khu mua sắm trung tâm Bắc Kinh, phù hợp cho khách muốn ở khu vực dễ di chuyển, nhiều tiện ích và thuận lợi cho cả tham quan lẫn ăn uống buổi tối.',
                'amenities' => json_encode(['Nhà hàng Hoa', 'Gym', 'Wifi', 'Gần phố đi bộ']),
                'image_url' => 'https://images.trvl-media.com/lodging/2000000/1170000/1167500/1167471/cc6b61b8.jpg?impolicy=resizecrop&rw=575&rh=575&ra=fill',
                'address' => '88 Dengshikou Street, Dongcheng, Beijing',
                'lat' => 39.917900,
                'lng' => 116.417400,
            ],
            [
                'location_id' => 39,
                'name' => 'L7 Myeongdong Seoul',
                'rating' => 4.7,
                'reviews_count' => 2140,
                'rating_text' => 'Xuất sắc',
                'price_per_night' => 3500000,
                'discount_percent' => 10,
                'is_promotion' => true,
                'promotion_end' => '2026-11-12 23:59:59',
                'combo_content' => 'Bao gồm bữa sáng, quyền dùng self-laundry, vị trí đi bộ tới Myeongdong shopping street, tiện ích lưu trú hiện đại và khả năng kết nối nhanh tới các khu mua sắm, ăn uống, tham quan nổi bật của trung tâm Seoul.',
                'description' => 'Khách sạn phong cách trẻ trung giữa trung tâm Seoul, phù hợp cho khách thích kết hợp tham quan và mua sắm nhờ vị trí đắc địa, không gian hiện đại và khả năng tiếp cận nhanh các khu phố sầm uất như Myeongdong hay Namdaemun.',
                'amenities' => json_encode(['Self-laundry', 'Cafe lounge', 'Wifi', 'Khu trung tâm']),
                'image_url' => 'https://images.trvl-media.com/lodging/13000000/12520000/12511700/12511672/8d20c3e7.jpg?impolicy=resizecrop&rw=575&rh=575&ra=fill',
                'address' => '137 Toegye-ro, Jung-gu, Seoul',
                'lat' => 37.561300,
                'lng' => 126.986200,
            ],
            [
                'location_id' => 11,
                'name' => 'Holiday Inn Resort Phuket',
                'rating' => 4.7,
                'reviews_count' => 1960,
                'rating_text' => 'Rất tốt',
                'price_per_night' => 3400000,
                'discount_percent' => 12,
                'is_promotion' => true,
                'promotion_end' => '2026-12-20 23:59:59',
                'combo_content' => 'Bao gồm buffet sáng mỗi ngày, quyền sử dụng hồ bơi ngoài trời, khu vui chơi trẻ em, hỗ trợ nhận phòng đoàn và vị trí đi bộ ra bãi biển Patong rất thuận tiện cho khách kết hợp nghỉ dưỡng, tắm biển và tự do khám phá khu trung tâm Phuket vào buổi tối.',
                'description' => 'Khách sạn nghỉ dưỡng nằm gần khu biển sôi động nhất Phuket, phù hợp với chương trình vừa tham quan vừa tự do vui chơi. Không gian xanh, nhiều hồ bơi và dịch vụ ổn định giúp dễ ghép thành combo bán tour ngắn ngày. Điểm mạnh của khách sạn là vị trí thuận tiện, khách có thể nhanh chóng tiếp cận bãi biển, khu mua sắm và các hoạt động giải trí buổi tối mà không mất nhiều thời gian di chuyển, nhờ đó trải nghiệm tour trở nên linh hoạt và dễ chịu hơn.',
                'amenities' => json_encode(['Hồ bơi', 'Khu vui chơi trẻ em', 'Buffet sáng', 'Gần biển']),
                'image_url' => 'https://images.trvl-media.com/lodging/1000000/10000/5000/4977/w3838h2560x2y0-35977ab1.jpg?impolicy=resizecrop&rw=575&rh=575&ra=fill',
                'address' => '52 Thaweewong Road, Patong, Phuket',
                'lat' => 7.889900,
                'lng' => 98.295000,
            ],
            [
                'location_id' => 26,
                'name' => 'Hotel The Celestine Kyoto Gion',
                'rating' => 4.8,
                'reviews_count' => 1320,
                'rating_text' => 'Xuất sắc',
                'price_per_night' => 5200000,
                'discount_percent' => 10,
                'is_promotion' => true,
                'promotion_end' => '2026-11-28 23:59:59',
                'combo_content' => 'Gói lưu trú gồm buffet sáng kiểu Nhật, khu tắm công cộng, xe shuttle nội khu, hỗ trợ gửi hành lý và vị trí thuận tiện để đi bộ tới Gion cùng nhiều đền chùa nổi tiếng, rất phù hợp cho chương trình tour thiên về văn hóa và trải nghiệm phố cổ.',
                'description' => 'Khách sạn mang phong cách thanh lịch, hiện đại nhưng vẫn giữ tinh thần Kyoto qua thiết kế tối giản, tông màu ấm và không gian yên tĩnh. Đây là lựa chọn phù hợp cho tour văn hóa vì vừa gần các điểm tham quan chính, vừa tạo cảm giác nghỉ dưỡng dễ chịu sau ngày di chuyển. Khi đưa vào combo tour, khách sạn này giúp nâng chất lượng cảm nhận của hành trình vì khách không chỉ đi tham quan Kyoto mà còn thật sự được sống trong không khí tinh tế, trầm lắng đặc trưng của cố đô.',
                'amenities' => json_encode(['Buffet sáng Nhật', 'Public bath', 'Wifi tốc độ cao', 'Gần khu Gion']),
                'image_url' => 'https://www.leafkyoto.net/leaf/wp-content/uploads/2022/09/220912-celestinegion-3-1-1024x683.jpg',
                'address' => '572 Komatsucho, Higashiyama-ku, Kyoto',
                'lat' => 35.000100,
                'lng' => 135.775100,
            ],
            [
                'location_id' => 41,
                'name' => 'Lotte City Hotel Jeju',
                'rating' => 4.6,
                'reviews_count' => 1180,
                'rating_text' => 'Rất tốt',
                'price_per_night' => 3100000,
                'discount_percent' => 10,
                'is_promotion' => true,
                'promotion_end' => '2026-12-05 23:59:59',
                'combo_content' => 'Bao gồm buffet sáng, hồ bơi ngoài trời theo mùa, xe đưa đón sân bay theo khung giờ, hỗ trợ check-in đoàn và vị trí thuận tiện để kết nối các điểm tham quan phía bắc đảo Jeju, khu mua sắm cũng như các cung đường ven biển nổi bật.',
                'description' => 'Khách sạn trung tâm có chất lượng ổn định, phù hợp cho đoàn khách cần chỗ nghỉ gọn gàng, dễ di chuyển và vẫn đảm bảo cảm giác nghỉ dưỡng nhẹ nhàng khi khám phá đảo Jeju. Từ đây có thể kết nối nhanh đến khu mua sắm, sân bay và nhiều cung đường ven biển đẹp, nhờ vậy lịch trình tour trở nên linh hoạt hơn và ít mất thời gian di chuyển. Đây là loại khách sạn dễ bán cho nhóm khách gia đình hoặc khách đi tour ghép vì cân bằng tốt giữa giá, vị trí và trải nghiệm lưu trú.',
                'amenities' => json_encode(['Buffet sáng', 'Hồ bơi', 'Xe sân bay', 'Khu mua sắm gần kề']),
                'image_url' => 'https://q-xx.bstatic.com/xdata/images/hotel/max500/467900645.jpg?k=aec097e39649c4789574ba0dd3f88200b7b12b36c56f7a379be46d973af7d7aa&o=',
                'address' => '83 Doryeong-ro, Jeju-si, Jeju',
                'lat' => 33.488900,
                'lng' => 126.486400,
            ],
        ];

        foreach ($hotels as &$hotel) {
            $hotel['created_at'] = $now;
            $hotel['updated_at'] = $now;
        }

        DB::table('hotels')->insert($hotels);
    }
}