<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class RestaurantSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();

        $restaurants = [
            [
                'location_id' => 1,
                'name' => 'Nhà hàng Hải Sản Bé Mặn',
                'rating' => 4.6,
                'reviews_count' => 1520,
                'min_price' => 150000,
                'max_price' => 800000,
                'discount_percent' => 10,
                'is_promotion' => true,
                'promotion_end' => '2026-12-31 23:59:59',
                'description' => 'Bé Mặn là cái tên bảo chứng cho hải sản tươi sống tại Đà Nẵng. Với không gian rộng rãi sát biển, thực khách có thể tự tay chọn hải sản đang bơi trong bể và yêu cầu đầu bếp chế biến tại chỗ, rất phù hợp cho khách đoàn hoặc gia đình muốn có bữa ăn vừa ngon vừa đúng chất biển miền Trung.',
                'menu' => json_encode([
                    ['name' => 'Tôm hùm xanh hấp', 'price' => 750000],
                    ['name' => 'Ghẹ xanh loại 1', 'price' => 450000],
                    ['name' => 'Mực lá nướng mọi', 'price' => 220000],
                    ['name' => 'Ốc hương rang muối', 'price' => 180000]
                ]),
                'amenities' => json_encode(['Wifi miễn phí', 'Máy điều hòa', 'Bãi đỗ xe rộng', 'Sát bờ biển']),
                'image_url' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2f/5a/85/33/caption.jpg?w=900&h=500&s=1',
                'address' => 'Lô 14 Hoàng Sa, Sơn Trà, Đà Nẵng',
                'lat' => 16.0675,
                'lng' => 108.2430,
            ],
            [
                'location_id' => 3,
                'name' => 'Phở Gia Truyền Bát Đàn',
                'rating' => 4.7,
                'reviews_count' => 3200,
                'min_price' => 40000,
                'max_price' => 80000,
                'discount_percent' => 0,
                'is_promotion' => false,
                'promotion_end' => null,
                'description' => 'Gói gọn tinh hoa phở Việt trong hơn nửa thế kỷ, phở Bát Đàn nổi tiếng với cảnh xếp hàng đợi mua mỗi sáng. Nước dùng trong, thanh vị xương ninh truyền thống và phong cách phục vụ mộc mạc khiến nơi đây trở thành điểm ăn rất đáng thử khi muốn cảm nhận đúng không khí ẩm thực Hà Nội.',
                'menu' => json_encode([
                    ['name' => 'Phở bò tái nạm', 'price' => 60000],
                    ['name' => 'Phở chín đặc biệt', 'price' => 55000],
                    ['name' => 'Quẩy giòn nóng', 'price' => 10000],
                    ['name' => 'Trứng chần', 'price' => 10000]
                ]),
                'amenities' => json_encode(['Không gian hoài cổ', 'Wifi', 'Phục vụ tận tâm']),
                'image_url' => 'https://mia.vn/media/uploads/blog-du-lich/Pho-bat-dan-pho-gia-truyen-100-nam-tuoi-tai-ha-noi-01-1639325605.jpg',
                'address' => '49 Bát Đàn, Hoàn Kiếm, Hà Nội',
                'lat' => 21.0340,
                'lng' => 105.8485,
            ],
            [
                'location_id' => 6,
                'name' => 'Nhà hàng Cua Vàng Hạ Long',
                'rating' => 4.5,
                'reviews_count' => 980,
                'min_price' => 200000,
                'max_price' => 1000000,
                'discount_percent' => 15,
                'is_promotion' => true,
                'promotion_end' => '2026-11-30 23:59:59',
                'description' => 'Đúng như tên gọi, nhà hàng là thiên đường cho các tín đồ mê cua biển Hạ Long. Không gian sang trọng, món ăn thiên về hải sản cao cấp và vị trí thuận tiện khiến nơi đây rất phù hợp cho những bữa tiệc, gặp mặt gia đình hoặc đoàn khách muốn dùng bữa trong không gian chỉn chu hơn.',
                'menu' => json_encode([
                    ['name' => 'Cua biển rang me', 'price' => 550000],
                    ['name' => 'Cua hấp nguyên con', 'price' => 480000],
                    ['name' => 'Lẩu hải sản Cua Vàng', 'price' => 850000],
                    ['name' => 'Miến xào cua', 'price' => 250000]
                ]),
                'amenities' => json_encode(['View biển cực đẹp', 'Phòng VIP riêng tư', 'Wifi', 'Dàn karaoke']),
                'image_url' => 'https://mia.vn/media/uploads/blog-du-lich/nha-hang-cua-vang-bai-chay-nha-hang-duy-nhat-o-viet-nam-co-mon-nay-1-1641883057.jpeg',
                'address' => '32 Phan Chu Trinh, Hạ Long',
                'lat' => 20.9550,
                'lng' => 107.0850,
            ],
            [
                'location_id' => 7,
                'name' => 'Lẩu Gà Lá É Tao Ngộ',
                'rating' => 4.6,
                'reviews_count' => 2100,
                'min_price' => 100000,
                'max_price' => 350000,
                'discount_percent' => 5,
                'is_promotion' => true,
                'promotion_end' => '2026-10-10 23:59:59',
                'description' => 'Món lẩu đặc trưng nhất Đà Lạt. Vị ngọt của gà ta hòa cùng vị cay nồng đặc trưng của lá é tạo nên sức hút khó cưỡng giữa không gian se lạnh, rất hợp cho khách đi nhóm hoặc gia đình muốn thưởng thức món địa phương đúng kiểu Đà Lạt về đêm.',
                'menu' => json_encode([
                    ['name' => 'Lẩu gà lá é (Lớn)', 'price' => 350000],
                    ['name' => 'Gỏi gà hành tây', 'price' => 150000],
                    ['name' => 'Cháo gà đậu xanh', 'price' => 80000]
                ]),
                'amenities' => json_encode(['Sân vườn rộng', 'View đồi núi', 'Không gian ấm cúng']),
                'image_url' => 'https://mia.vn/media/uploads/blog-du-lich/lau-ga-la-e-tao-ngo-da-lat-pham-ngu-lao-1722768560.jpg',
                'address' => '5 Đường 3/4, Đà Lạt',
                'lat' => 11.9415,
                'lng' => 108.4419,
            ],
            [
                'location_id' => 8,
                'name' => 'Ra Khơi Restaurant Phú Quốc',
                'rating' => 4.7,
                'reviews_count' => 1750,
                'min_price' => 200000,
                'max_price' => 900000,
                'discount_percent' => 20,
                'is_promotion' => true,
                'promotion_end' => '2026-09-01 23:59:59',
                'description' => 'Ra Khơi là điểm đến ẩm thực không thể bỏ qua tại trung tâm Dương Đông. Nhà hàng nổi tiếng với nguồn nguyên liệu tươi rói từ đảo Ngọc, thực đơn phong phú và không khí ăn uống sôi động, rất thích hợp cho khách du lịch muốn thưởng thức hải sản đúng chất Phú Quốc.',
                'menu' => json_encode([
                    ['name' => 'Nhum biển nướng trứng', 'price' => 55000],
                    ['name' => 'Ốc hương rang muối', 'price' => 280000],
                    ['name' => 'Cá mú nướng mọi', 'price' => 450000],
                    ['name' => 'Tôm mũ ni cháy tỏi', 'price' => 750000]
                ]),
                'amenities' => json_encode(['View biển thoáng mát', 'BBQ ngoài trời', 'Wifi', 'Bãi đỗ xe']),
                'image_url' => 'https://d2kihw5e8drjh5.cloudfront.net/eyJidWNrZXQiOiJ1dGEtaW1hZ2VzIiwia2V5IjoicGxhY2VfaW1nL3Z0SnRabF9lVEl5Zmh4ZUs0ZVJrclEiLCJlZGl0cyI6eyJyZXNpemUiOnsid2lkdGgiOjY0MCwiaGVpZ2h0Ijo2NDAsImZpdCI6Imluc2lkZSJ9LCJyb3RhdGUiOm51bGwsInRvRm9ybWF0IjogIndlYnAifX0=',
                'address' => '131 Đường 30/4, Dương Đông, Phú Quốc',
                'lat' => 10.2190,
                'lng' => 103.9600,
            ],
            [
                'location_id' => 9,
                'name' => 'Sala Rattanakosin Bangkok',
                'rating' => 4.6,
                'reviews_count' => 1420,
                'min_price' => 250000,
                'max_price' => 1200000,
                'discount_percent' => 10,
                'is_promotion' => true,
                'promotion_end' => '2026-11-20 23:59:59',
                'description' => 'Nhà hàng rooftop nhìn thẳng ra sông Chao Phraya và Wat Arun, phù hợp cho bữa tối ngắm Bangkok lên đèn, đặc biệt lý tưởng với du khách thích không gian lãng mạn, cảnh đẹp và muốn kết hợp trải nghiệm ẩm thực với ngắm toàn cảnh thành phố cổ ven sông.',
                'menu' => json_encode([
                    ['name' => 'Pad Thai tôm sông', 'price' => 280000],
                    ['name' => 'Tom Yum hải sản', 'price' => 320000],
                    ['name' => 'Cà ri xanh gà', 'price' => 260000],
                    ['name' => 'Xôi xoài', 'price' => 140000]
                ]),
                'amenities' => json_encode(['View sông', 'Bàn ngoài trời', 'Wifi', 'Cocktail bar']),
                'image_url' => 'https://www.salahospitality.com/rattanakosin-bangkok/wp-content/uploads/sites/4/2024/09/8.-rooftop-bar-opening-hours-sala-rattanakosin-Bangkok.jpg',
                'address' => '39 Maharat Road, Phra Nakhon, Bangkok',
                'lat' => 13.7467,
                'lng' => 100.4902,
            ],
            [
                'location_id' => 15,
                'name' => 'Kualao Restaurant Vientiane',
                'rating' => 4.5,
                'reviews_count' => 860,
                'min_price' => 120000,
                'max_price' => 550000,
                'discount_percent' => 5,
                'is_promotion' => true,
                'promotion_end' => '2026-10-15 23:59:59',
                'description' => 'Điểm ăn tối nổi tiếng tại Viêng Chăn với các món Lào truyền thống và chương trình múa dân gian vào buổi tối, giúp du khách vừa dùng bữa vừa cảm nhận rõ nét văn hóa bản địa trong một không gian lịch sự và dễ tiếp cận với khách đoàn.',
                'menu' => json_encode([
                    ['name' => 'Lạp bò', 'price' => 180000],
                    ['name' => 'Xúc xích Lào nướng', 'price' => 150000],
                    ['name' => 'Cá sông Mekong hấp', 'price' => 320000],
                    ['name' => 'Xôi nếp Lào', 'price' => 60000]
                ]),
                'amenities' => json_encode(['Biểu diễn truyền thống', 'Phòng máy lạnh', 'Wifi', 'Bãi đỗ xe']),
                'image_url' => 'https://upload.wikimedia.org/wikipedia/commons/9/9a/Kualao_Restaurant_in_Vientiane%2C_Laos_%282014%29.jpg',
                'address' => '134 Samsenthai Road, Vientiane',
                'lat' => 17.9668,
                'lng' => 102.6087,
            ],
            [
                'location_id' => 18,
                'name' => 'Malis Siem Reap',
                'rating' => 4.7,
                'reviews_count' => 1180,
                'min_price' => 180000,
                'max_price' => 780000,
                'discount_percent' => 10,
                'is_promotion' => true,
                'promotion_end' => '2026-11-05 23:59:59',
                'description' => 'Nhà hàng Khmer cao cấp với sân vườn nhiệt đới, rất hợp để ghép cùng hành trình tham quan Angkor Wat vì vừa có không gian đẹp, thực đơn chỉn chu, vừa mang lại cảm giác thư giãn sau một ngày tham quan di tích khá dày.',
                'menu' => json_encode([
                    ['name' => 'Cà ri cá Amok', 'price' => 260000],
                    ['name' => 'Bò lúc lắc Khmer', 'price' => 290000],
                    ['name' => 'Gỏi xoài hải sản', 'price' => 210000],
                    ['name' => 'Kem dừa thốt nốt', 'price' => 90000]
                ]),
                'amenities' => json_encode(['Sân vườn', 'Phòng riêng', 'Wifi', 'Phục vụ đoàn']),
                'image_url' => 'https://malis.thalias.com.kh/wp-content/uploads/2024/07/F3384V17-scaled.jpg',
                'address' => 'Pokambor Avenue, Siem Reap',
                'lat' => 13.3615,
                'lng' => 103.8568,
            ],
            [
                'location_id' => 21,
                'name' => 'Bebek Tepi Sawah Ubud',
                'rating' => 4.6,
                'reviews_count' => 2050,
                'min_price' => 150000,
                'max_price' => 650000,
                'discount_percent' => 10,
                'is_promotion' => true,
                'promotion_end' => '2026-12-05 23:59:59',
                'description' => 'Nhà hàng giữa cánh đồng lúa Ubud, nổi tiếng với món vịt chiên giòn Bali và không gian thư giãn, rất phù hợp cho khách thích trải nghiệm dùng bữa gần gũi thiên nhiên và cảm nhận trọn vẹn vẻ yên bình rất riêng của Bali.',
                'menu' => json_encode([
                    ['name' => 'Vịt chiên giòn Bali', 'price' => 240000],
                    ['name' => 'Sate Lilit', 'price' => 180000],
                    ['name' => 'Cơm chiên Nasi Goreng', 'price' => 140000],
                    ['name' => 'Nước dừa tươi', 'price' => 50000]
                ]),
                'amenities' => json_encode(['View ruộng lúa', 'Khu ngoài trời', 'Wifi', 'Nhạc sống']),
                'image_url' => 'https://www.pelago.com/img/products/ID-Indonesia/bebek-tepi-sawah-restaurant/0710-0632_bebek-tepi-sawah-restaurant-indonesia-pelago7.jpg',
                'address' => 'Jl. Raya Goa Gajah, Ubud, Bali',
                'lat' => -8.5298,
                'lng' => 115.2746,
            ],
            [
                'location_id' => 25,
                'name' => 'Asakusa Imahan Tokyo',
                'rating' => 4.8,
                'reviews_count' => 970,
                'min_price' => 600000,
                'max_price' => 2500000,
                'discount_percent' => 0,
                'is_promotion' => false,
                'promotion_end' => null,
                'description' => 'Nhà hàng sukiyaki lâu đời gần Senso-ji, phù hợp cho trải nghiệm ẩm thực Tokyo truyền thống, đặc biệt với khách muốn thưởng thức món Nhật cao cấp trong không gian chỉn chu và đậm dấu ấn văn hóa địa phương.',
                'menu' => json_encode([
                    ['name' => 'Sukiyaki bò Wagyu', 'price' => 1650000],
                    ['name' => 'Shabu shabu thượng hạng', 'price' => 1450000],
                    ['name' => 'Tempura tôm', 'price' => 420000],
                    ['name' => 'Matcha pudding', 'price' => 120000]
                ]),
                'amenities' => json_encode(['Phòng tatami', 'Đặt bàn riêng', 'Wifi', 'Phục vụ tiếng Anh']),
                'image_url' => 'https://imahan-tokyo.com/wp-content/uploads/2021/08/asakusa-imahan.jpg',
                'address' => '1-19-7 Asakusa, Taito City, Tokyo',
                'lat' => 35.7147,
                'lng' => 139.7967,
            ],
            [
                'location_id' => 32,
                'name' => 'Palm Beach Seafood Singapore',
                'rating' => 4.6,
                'reviews_count' => 1880,
                'min_price' => 350000,
                'max_price' => 1800000,
                'discount_percent' => 10,
                'is_promotion' => true,
                'promotion_end' => '2026-09-30 23:59:59',
                'description' => 'Nhà hàng hải sản nổi tiếng ngay khu Merlion Park, phù hợp cho khách đi city tour trung tâm Singapore vì vừa thuận tiện di chuyển, vừa có thực đơn đặc trưng như Chili Crab và không gian nhìn ra khu Marina rất đẹp.',
                'menu' => json_encode([
                    ['name' => 'Chili Crab', 'price' => 980000],
                    ['name' => 'Cereal Prawn', 'price' => 420000],
                    ['name' => 'Sò điệp sốt bơ tỏi', 'price' => 360000],
                    ['name' => 'Nước ép trái cây nhiệt đới', 'price' => 90000]
                ]),
                'amenities' => json_encode(['View Marina Bay', 'Phòng máy lạnh', 'Wifi', 'Phục vụ đoàn']),
                'image_url' => 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-F0gFEpahODQFVT04fuWV6cCrydGSPHPk3Q&s',
                'address' => '1 Fullerton Road, One Fullerton, Singapore',
                'lat' => 1.2863,
                'lng' => 103.8537,
            ],
            [
                'location_id' => 35,
                'name' => 'Quanjude Roast Duck Beijing',
                'rating' => 4.5,
                'reviews_count' => 2310,
                'min_price' => 300000,
                'max_price' => 1500000,
                'discount_percent' => 5,
                'is_promotion' => true,
                'promotion_end' => '2026-10-25 23:59:59',
                'description' => 'Chuỗi vịt quay lâu đời bậc nhất Bắc Kinh, thích hợp cho lịch trình tham quan Vạn Lý Trường Thành và trung tâm thành phố, đặc biệt phù hợp với khách muốn thử món ăn biểu tượng của Bắc Kinh trong không gian phục vụ chuyên nghiệp và đậm màu sắc địa phương.',
                'menu' => json_encode([
                    ['name' => 'Vịt quay Bắc Kinh nguyên con', 'price' => 980000],
                    ['name' => 'Sủi cảo tôm thịt', 'price' => 180000],
                    ['name' => 'Đậu phụ Tứ Xuyên', 'price' => 160000],
                    ['name' => 'Trà hoa nhài', 'price' => 80000]
                ]),
                'amenities' => json_encode(['Phòng riêng', 'Wifi', 'Phục vụ đoàn', 'Khu trung tâm']),
                'image_url' => 'https://www.palmbeachseafood.com/images/visit-us-img.jpg',
                'address' => '30 Qianmen Street, Dongcheng, Beijing',
                'lat' => 39.8987,
                'lng' => 116.3975,
            ],
            [
                'location_id' => 39,
                'name' => 'Myeongdong Kyoja Seoul',
                'rating' => 4.7,
                'reviews_count' => 3420,
                'min_price' => 120000,
                'max_price' => 450000,
                'discount_percent' => 0,
                'is_promotion' => false,
                'promotion_end' => null,
                'description' => 'Nhà hàng mì cắt và mandu nổi tiếng ở Myeongdong, hợp cho khách muốn thử món địa phương chuẩn vị Seoul trong không gian trung tâm, phục vụ nhanh và rất thuận tiện để ghép vào lịch trình tham quan kết hợp mua sắm.',
                'menu' => json_encode([
                    ['name' => 'Kalguksu', 'price' => 140000],
                    ['name' => 'Mandu hấp', 'price' => 150000],
                    ['name' => 'Bibim guksu', 'price' => 135000],
                    ['name' => 'Kimchi', 'price' => 50000]
                ]),
                'amenities' => json_encode(['Phục vụ nhanh', 'Wifi', 'Khu trung tâm', 'Điều hòa']),
                'image_url' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0d/5c/f3/7d/myeongdong-kyoja.jpg?w=1200&h=900&s=1',
                'address' => '29 Myeongdong 10-gil, Jung-gu, Seoul',
                'lat' => 37.5633,
                'lng' => 126.9853,
            ],
            [
                'location_id' => 11,
                'name' => 'Kan Eang @ Pier Phuket',
                'rating' => 4.6,
                'reviews_count' => 1560,
                'min_price' => 220000,
                'max_price' => 980000,
                'discount_percent' => 10,
                'is_promotion' => true,
                'promotion_end' => '2026-12-10 23:59:59',
                'description' => 'Nhà hàng hải sản ven biển nổi tiếng của Phuket với không gian mở nhìn ra bến tàu Chalong, rất phù hợp để đưa vào chương trình ăn tối cho đoàn khách thích trải nghiệm đúng chất biển đảo Thái Lan. Thực đơn thiên về hải sản tươi, món nướng và cà ri đậm vị địa phương, trong khi không khí nhà hàng lại khá thoáng, dễ ngồi lâu và chụp ảnh đẹp lúc chiều muộn. Đây là kiểu điểm ăn uống vừa có trải nghiệm cảnh quan, vừa đủ chất lượng để làm nổi bật giá trị của tour Phuket.',
                'menu' => json_encode([
                    ['name' => 'Tôm nướng sốt me', 'price' => 320000],
                    ['name' => 'Cà ri cua kiểu Phuket', 'price' => 410000],
                    ['name' => 'Mực nướng sa tế Thái', 'price' => 260000],
                    ['name' => 'Gỏi đu đủ hải sản', 'price' => 180000]
                ]),
                'amenities' => json_encode(['View biển', 'Không gian mở', 'Wifi', 'Phục vụ đoàn']),
                'image_url' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/15/f2/4f/49/kan-eang-pier.jpg?w=1200&h=900&s=1',
                'address' => '44/1 Viset Road, Chalong, Phuket',
                'lat' => 7.8263,
                'lng' => 98.3386,
            ],
            [
                'location_id' => 26,
                'name' => 'Kyoto Gogyo',
                'rating' => 4.7,
                'reviews_count' => 1280,
                'min_price' => 250000,
                'max_price' => 720000,
                'discount_percent' => 0,
                'is_promotion' => false,
                'promotion_end' => null,
                'description' => 'Nhà hàng nổi tiếng tại Kyoto với phong cách phục vụ chỉn chu và món ramen cháy đặc trưng tạo nên dấu ấn rất riêng. Đây là lựa chọn hợp lý cho tour cố đô vì vừa đủ hiện đại để dễ ăn với khách Việt, vừa giữ được tinh thần ẩm thực Nhật truyền thống trong không gian ấm cúng giữa khu phố cổ. Khi đưa vào chương trình tour, điểm này giúp phần ẩm thực không bị quá đơn điệu mà vẫn gắn chặt với trải nghiệm Kyoto mang tính bản sắc.',
                'menu' => json_encode([
                    ['name' => 'Kogashi miso ramen', 'price' => 320000],
                    ['name' => 'Gyoza áp chảo', 'price' => 180000],
                    ['name' => 'Cơm thịt bò Nhật', 'price' => 260000],
                    ['name' => 'Trà xanh Kyoto', 'price' => 90000]
                ]),
                'amenities' => json_encode(['Không gian Nhật', 'Wifi', 'Phục vụ nhanh', 'Khu trung tâm']),
                'image_url' => 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/0f/46/27/4c/gogyo-kyoto.jpg?w=1200&h=900&s=1',
                'address' => '452 Matsugae-cho, Nakagyo-ku, Kyoto',
                'lat' => 35.0062,
                'lng' => 135.7649,
            ],
            [
                'location_id' => 41,
                'name' => 'Haenyeo Kitchen Jeju',
                'rating' => 4.6,
                'reviews_count' => 940,
                'min_price' => 180000,
                'max_price' => 680000,
                'discount_percent' => 5,
                'is_promotion' => true,
                'promotion_end' => '2026-11-15 23:59:59',
                'description' => 'Nhà hàng mang cảm hứng từ văn hóa haenyeo, nổi bật với thực đơn hải sản tươi, các món súp nóng và thịt heo đen đặc trưng của đảo Jeju. Không gian sáng sủa, phục vụ gọn gàng, phù hợp cho khách đoàn nhỏ hoặc nhóm gia đình muốn có bữa ăn đủ đậm chất địa phương nhưng vẫn dễ dùng. Đây là điểm ăn hợp lý để đưa vào chương trình sau một ngày tham quan cung đường ven biển, vì vừa tạo cảm giác ấm cúng, vừa giúp khách nhớ rõ bản sắc ẩm thực Jeju.',
                'menu' => json_encode([
                    ['name' => 'Lẩu hải sản Jeju', 'price' => 420000],
                    ['name' => 'Thịt heo đen nướng', 'price' => 390000],
                    ['name' => 'Bào ngư hấp', 'price' => 350000],
                    ['name' => 'Canh rong biển', 'price' => 160000]
                ]),
                'amenities' => json_encode(['Gần biển', 'Phòng máy lạnh', 'Wifi', 'Phục vụ đoàn']),
                'image_url' => 'https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&w=1200&q=80',
                'address' => '20 Seopjikoji-ro, Seogwipo-si, Jeju',
                'lat' => 33.4324,
                'lng' => 126.9276,
            ],
        ];

        foreach ($restaurants as &$restaurant) {
            $restaurant['created_at'] = $now;
            $restaurant['updated_at'] = $now;
        }

        DB::table('restaurants')->insert($restaurants);
    }
}